# Generated by Django 2.2.3 on 2020-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reletionship',
            field=models.CharField(choices=[('Mum', 'mum'), ('Sister', 'sister'), ('Brother', 'brother'), ('Friend', 'friend')], max_length=7, null=True),
        ),
    ]
