# Generated by Django 2.2.3 on 2020-04-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0002_person_reletionship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='reletionship',
            new_name='relationship',
        ),
    ]
