# Generated by Django 3.2.3 on 2021-06-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframework', '0004_auto_20200429_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='just not to confuse each other any descriptive text', max_length=200, null=True)),
                ('brand', models.CharField(max_length=200)),
                ('model_no', models.CharField(blank=True, help_text='wmic computersystem get model,name', max_length=200, null=True)),
                ('serial_no', models.CharField(blank=True, help_text='wmic bios get serialnumber', max_length=200, null=True, unique=True)),
                ('node_name', models.CharField(blank=True, help_text='wmic computersystem get name', max_length=200, null=True)),
                ('type_of_computer', models.CharField(blank=True, choices=[['PC', 'PC'], ['PHONE', 'PHONE'], ['PRINTER', 'PRINTER'], ['DLINK_SWITCH', 'DLINK SWITCH'], ['CISCO_SWITCH', 'CISCO SWITCH']], max_length=200, null=True)),
                ('processor', models.CharField(blank=True, max_length=200, null=True)),
                ('ram_size', models.CharField(blank=True, max_length=200, null=True)),
                ('hdd_size', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[['Active', 'Active'], ['In_Active', 'In Active'], ['Dead', 'Dead']], max_length=20, null=True)),
                ('assiend_end_user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
